import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Body from '../components/body'
import Footer from '../components/footer'


export default function Home() {
  return (
    <div className='flex flex-col justify-center h-screen items-center'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header></Header>
    <Body/>
    <Footer/>
  
    </div>
  )
}
